# Generated by Django 5.1.1 on 2024-09-23 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='timeLogs',
        ),
        migrations.AddField(
            model_name='timelog',
            name='activity',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ActivityTracker.activity'),
            preserve_default=False,
        ),
    ]
