# Generated by Django 5.1.1 on 2024-09-23 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityTracker', '0002_remove_activity_timelogs_timelog_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeLogs', to='ActivityTracker.activity'),
        ),
    ]
