# Generated by Django 5.1.1 on 2024-09-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityTracker', '0003_alter_timelog_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='timeSpent',
            field=models.DateField(default='2024-05-13'),
            preserve_default=False,
        ),
    ]
